add xsky block csi charts to rancher
cnrancher/pandaria-catalog pull request #12
Opened 2019-11-13 06:56 UTC by zhucan

Signed-off-by: zhuc <zhucan@xsky.com>

2019-11-14 08:06 UTC, Jason-ZW requested changes
It's best to include content in `README.md` and it doesn't matter if you don't accept it.
Others LGTM.

2019-11-14 08:06 UTC, Jason-ZW commented on charts/xsky/v2.0.1/questions.yaml
> +         default: "2.1.0"
Is that version correct?  Maybe `2.0.1` not `2.1.0`?

2019-11-26 05:20 UTC, Jason-ZW commented on charts/xsky/v2.1.0/templates/nodeplugin-daemonset.yaml
> +		    - name: socket-dir
Could you please modify the indent?

2019-11-26 05:30 UTC, Jason-ZW commented on charts/xsky/v2.1.0/templates/nodeplugin-daemonset.yaml
> +		    - name: socket-dir
Could you please change the indent?

2019-11-26 06:55 UTC, zhucan commented on charts/xsky/v2.1.0/templates/nodeplugin-daemonset.yaml
> +		    - name: socket-dir
I will do it out of day

2019-11-26 06:56 UTC, zhucan commented on charts/xsky/v2.0.1/questions.yaml
> +         default: "2.1.0"
README.md has been added

2019-11-26 07:12 UTC, Jason-ZW approved these changes

2019-11-26 07:14 UTC, merged