[2.7] Add gpu share v2 charts(sharing and monitoring)
cnrancher/pandaria-catalog pull request #136
Opened 2023-03-06 08:01 UTC by jianghang8421

## Issue

https://github.com/cnrancher/pandaria/issues/2742
 
## Problem

1. 模块解耦。通过 cluster-tool 对 GPU sharing功能进行部署管理。
2. rancher gpu sharing 能够支持RKE RKE2 K3S集群。
3. 支持新的GPU监控并对接到Rancher的监控中。通过 cluster-tool 进行部署管理。
 
## Solution

1. 新增 rancher-gpu-sharing chart。作为cluster-tool在Rancher中进行部署管理。
2. 新增 rancher-gpu-monitoring chart。作为cluster-tool在Rancher中进行部署管理。

## Engineering Testing
### Manual Testing

1. rancher-gpu-sharing 部署到RKE ，RKE2，K3S环境，并进行GPU共享调度功能测试。
2. rancher-gpu-monitoring 部署测试。GPU节点监控图表数据测试。

### Automated Testing

https://github.com/cnrancher/pandaria-tests/pull/39

## QA Testing Considerations
### Regressions Considerations

需要针对RKE，RKE2，K3S场景进行验证。GPU共享调度功能使用上没有变化。

2023-03-06 08:14 UTC, STARRY-S approved these changes
LGTM

- [x] `Chart.yaml` 中是否配置 `catalog.cattle.io/rancher-version`
- [x] `Chart.yaml` 中是否配置 `catalog.cattle.io/kube-version`
- [x] 是否支持 `systemDefaultRegistry` 设置
- [x] 容器镜像是否为 Manifest 且 Project 为 rancher/cnrancher 
- [x] `values.yaml` 中容器镜像是否可以在 Rancher 构建镜像列表时被识别

2023-03-08 09:59 UTC, Jason-ZW requested changes

2023-03-08 09:59 UTC, Jason-ZW commented on charts/rancher-gpu-monitoring/0.0.1/questions.yml
> +rancher_min_version: 2.7.0
这里要在开放到2.7.0么？貌似 Chart.yaml 里限定是 >= 2.7.2-0

2023-03-08 09:59 UTC, Jason-ZW commented on charts/rancher-gpu-sharing/0.0.1/questions.yml
> +rancher_min_version: 2.7.0
同样疑问

2023-03-08 09:59 UTC, Jason-ZW commented on charts/rancher-gpu-sharing/0.0.1/questions.yml
> +  default: "v1.23"
2.7.2 是否要以1.25为default

2023-03-08 09:59 UTC, Jason-ZW commented on packages/rancher-gpu-monitoring/v0.0.1/questions.yml
> +rancher_min_version: 2.7.0
同样问题

2023-03-08 09:59 UTC, Jason-ZW commented on packages/rancher-gpu-sharing/v0.0.1/questions.yml
> +  default: "v1.23"
同样疑问

2023-03-08 09:59 UTC, Jason-ZW commented on packages/rancher-gpu-sharing/v0.0.1/values.yaml
> +    tag: "v0.1.2-rc1"
请确认rc版本是否为预期

2023-03-08 10:00 UTC, jianghang8421 commented on charts/rancher-gpu-monitoring/0.0.1/questions.yml
> +rancher_min_version: 2.7.0
已修改为2.7.2

2023-03-08 10:01 UTC, jianghang8421 commented on charts/rancher-gpu-sharing/0.0.1/questions.yml
> +rancher_min_version: 2.7.0
已修改为2.7.2

2023-03-08 10:01 UTC, jianghang8421 commented on packages/rancher-gpu-monitoring/v0.0.1/questions.yml
> +rancher_min_version: 2.7.0
已修改为2.7.2

2023-03-08 10:01 UTC, jianghang8421 commented on packages/rancher-gpu-sharing/v0.0.1/questions.yml
> +  default: "v1.23"
已修改为2.7.2

2023-03-08 10:01 UTC, jianghang8421 commented on packages/rancher-gpu-sharing/v0.0.1/values.yaml
> +    tag: "v0.1.2-rc1"
目前是rc版本。测试后才能发正式版。

2023-03-08 10:04 UTC, jianghang8421 commented on charts/rancher-gpu-sharing/0.0.1/questions.yml
> +  default: "v1.23"
已改为默认1.25

2023-03-09 01:54 UTC, JacieChao reviewed
Others LGTM

2023-03-09 01:54 UTC, JacieChao commented on charts/rancher-gpu-monitoring/0.0.1/templates/daemonset.yaml
> +        image: "{{ template "system_default_registry" . }}{{ .Values.image.repository }}:{{ .Values.image.tag }}"
这里是不是可以这样写：
image: {{ template "system_default_registry" . }}{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}

2023-03-09 02:06 UTC, jianghang8421 commented on charts/rancher-gpu-monitoring/0.0.1/templates/daemonset.yaml
> +        image: "{{ template "system_default_registry" . }}{{ .Values.image.repository }}:{{ .Values.image.tag }}"
效果应该是一样的。不过这里我倾向于不改，因为这部分是来自于[上游NVIDIA/dcgm-exporter的部署chart ](https://github.com/NVIDIA/dcgm-exporter/blob/ea30b622585da2b21b27fdfc16971f69d1a42c1a/deployment/templates/daemonset.yaml#L82) 。只修改我们需要变更的地方方便后续更新时进行merge。

2023-03-09 02:13 UTC, JacieChao commented on charts/rancher-gpu-monitoring/0.0.1/templates/daemonset.yaml
> +        image: "{{ template "system_default_registry" . }}{{ .Values.image.repository }}:{{ .Values.image.tag }}"
ok，其他的我没问题了

2023-03-09 02:14 UTC, JacieChao approved these changes

2023-03-09 02:19 UTC, Jason-ZW approved these changes

2023-03-09 02:19 UTC, merged