QFusion: update version
cnrancher/pandaria-catalog pull request #31
Opened 2021-06-19 08:39 UTC by llhhbc

1. add rds config

Signed-off-by: lilonghui <longhui.li@woqutech.com>

2021-06-28 03:33 UTC, Jason-ZW commented
why remove ` charts/qfusion/woqutech.png`? I think Charts.yml using this png file.

2021-06-28 03:59 UTC, Jason-ZW approved these changes

2021-06-28 05:06 UTC, Jason-ZW requested changes
Need test on rancher custom cluster.

2021-07-27 06:23 UTC, llhhbc commented
test ok

2021-08-02 06:34 UTC, merged